services:
  postgres:
    image: postgres:18-alpine
    container_name: maild-postgres
    environment:
      POSTGRES_DB: maild
      POSTGRES_USER: maild
      POSTGRES_PASSWORD: maild
    ports:
      - "5432:5432"
    volumes:
      - maild_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U maild -d maild"]
      interval: 5s
      timeout: 3s
      retries: 20

  redis:
    image: redis:8.6.2-alpine
    container_name: maild-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - maild_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  mailpit:
    image: axllent/mailpit:latest
    container_name: maild-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  maild_postgres_data:
  maild_redis_data:
